export const GET_SPRINTS = 'GET_SPRINTS';
export const ADD_SPRINT = 'ADD_SPRINT';
export const GET_NOMINATIONS = 'GET_NOMINATIONS';
export const ADD_NOMINATION_TO_SPRINT = 'ADD_NOMINATION_TO_SPRINT';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
